### ISSUE TITLE
Add structure and content to news page

### ISSUE THREAD

**Issue by anotherjoshsmith** [UWPRG/UWPRG.github.io#15]
We need to create a group news page for the website, in `news.html`. I think at group meeting last week @jnnsmpth volunteered to help with this. I have assigned this issue to her for content, and to myself for structure. Basically what we need is 4 or 5 news events, with a picture and brief synopsis of each. 

@pfaendtner can you think of any recent newsworthy events for us to start with? off the top of my head, i'm thinking GRFP for @sarahalamdari, FOMMS talk for you, welcoming @jnnsmpth to the group, and a post about the FHL retreat.

**Comment by pfaendtner** [comment]
addressed by #32
