### ISSUE TITLE
Main page cleanup

### ISSUE THREAD

**Issue by pfaendtner** [UWPRG/UWPRG.github.io#21]
Can we make the following changes on index.html: 

1) I think we want everything starting w/the 1st "A Major Heading" and below it gone, right? 

2) I'm not feeling the dark green.  can you swap it out with one of the grey background colors from the molecule image?

**Comment by anotherjoshsmith** [comment]
1. I was planning to choose 3 of the stories from `news.html` to be featured on the homepage below the 1st "A Major Heading". I'll delete everything else. 
2. No problem, I'll get rid of the dark green.

**Comment by pfaendtner** [comment]
this sounds great


On Sep 5, 2018, at 4:38 PM, Josh Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  I was planning to choose 3 of the stories from news.html to be featured on the homepage below the 1st "A Major Heading". I'll delete everything else.
  2.  No problem, I'll get rid of the dark green.
