### ISSUE TITLE
pubs page

### ISSUE THREAD

**Issue by pfaendtner** [UWPRG/UWPRG.github.io#23]
Until pubs page is ready can we redirect to Google Scholar?

**Comment by anotherjoshsmith** [comment]
@pfaendtner have you checked out the `update-pubs` branch and associated PR #17? The approach for continued updates is semi-automated for now.

**Comment by pfaendtner** [comment]
I can’t even see any branches on the new version - is it there?!

/Users/jpfaendt/Research Group/UWPRG.github.io<http://UWPRG.github.io>
Jims-MBP-2:UWPRG.github.io<http://UWPRG.github.io> jpfaendt$ git branch -l
* master



On Sep 5, 2018, at 4:42 PM, Josh Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


@pfaendtner<https://github.com/pfaendtner> have you checked out the update-pubs branch and associated PR #17<https://github.com/UWPRG/UWPRG.github.io/pull/17>? The approach for continued updates is semi-automated for now.

**Comment by anotherjoshsmith** [comment]
try: `git branch --remote` to see the branches.

`git checkout update-pubs`  should work if you have cloned the new repo

**Comment by pfaendtner** [comment]
all good now

**Comment by anotherjoshsmith** [comment]
Addressed by #17
