### ISSUE TITLE
research page title

### ISSUE THREAD

**Issue by pfaendtner** [UWPRG/UWPRG.github.io#25]
can someone please fix the title of the research page and high level text:

OUR RESEARCH (OR SOME TITLE)

High-level overview of our research. What are the common tools/approaches that unite all of the research areas detailed below?

I can't find it in the html files , is it in the css? 

Do we need this information here or a title? 

If you want a few sentences at the top you could do something like the following (please proofread): 

Our group uses computer simulations to understand and control molecular scale driving forces for a wide range of applications spanning biotechnology to fuel combustion. We develop new methods that expand the capabilities of molecular simulation and use advanced research computing resources to solve challenging problems in the area of computational molecular science. A few representative projects are described below.

**Comment by ldgibson** [comment]
created `research-title` branch and added the intro that @pfaendtner wrote.

**Comment by anotherjoshsmith** [comment]
Thanks, @ldgibson! Can you please create a PR for this?

**Comment by anotherjoshsmith** [comment]
Addressed by #26.
